# Generated by Django 5.1.6 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.FloatField(default=2.5)),
                ('per_km_rate', models.FloatField(default=1.0)),
                ('traffic_multiplier_high', models.FloatField(default=1.5)),
                ('demand_multiplier_peak', models.FloatField(default=1.8)),
            ],
        ),
    ]
